import type { Agency, Analytics, Review } from './types'; import type { AuthUser } from './auth';
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
type ApiResult<T> = { success: boolean; data: T; message?: string; pagination?: { total: number; page?: number; pages?: number }; user?: AuthUser; ratingBreakdown?: Record<number, number> };
const request = async <T>(path: string, options: RequestInit = {}): Promise<ApiResult<T>> => { const response = await fetch(`${API_URL}${path}`, { credentials: 'include', ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || 'The request could not be completed.'); return payload; };
export const getAgencies = (params: URLSearchParams) => request<Agency[]>(`/agencies?${params}`); export const getAgency = (id: string) => request<Agency>(`/agencies/${id}`); export const getAnalytics = () => request<Analytics>('/analytics');
export const login = (email: string, password: string) => request<never>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); export const signup = (name: string, email: string, password: string) => request<never>('/auth/signup', { method: 'POST', body: JSON.stringify({ name, email, password }) }); export const authMe = () => request<never>('/auth/me'); export const logout = () => request<never>('/auth/logout', { method: 'POST' }); export const getProfile = () => request<AuthUser & { reviewsWritten: number; savedAgencies: number }>('/auth/profile'); export const updateProfile = (name: string) => request<never>('/auth/profile', { method: 'PATCH', body: JSON.stringify({ name }) }); export const changePassword = (currentPassword: string, newPassword: string) => request<never>('/auth/password', { method: 'PATCH', body: JSON.stringify({ currentPassword, newPassword }) });
export const getReviews = (agencyId: string, page = 1) => request<Review[]>(`/reviews/agency/${agencyId}?page=${page}&limit=10`); export const submitReview = (agencyId: string, data: { rating: number; title: string; text: string; services: string[] }) => request<Review>(`/reviews/agency/${agencyId}`, { method: 'POST', body: JSON.stringify(data) }); export const updateReview = (id: string, data: Partial<{ rating: number; title: string; text: string; services: string[] }>) => request<Review>(`/reviews/${id}`, { method: 'PATCH', body: JSON.stringify(data) }); export const deleteReview = (id: string) => request<never>(`/reviews/${id}`, { method: 'DELETE' });
export const getBookmarks = () => request<Array<{ agency: Agency }>>('/bookmarks'); export const addBookmark = (agencyId: string) => request<unknown>(`/bookmarks/${agencyId}`, { method: 'POST' }); export const removeBookmark = (agencyId: string) => request<never>(`/bookmarks/${agencyId}`, { method: 'DELETE' });
export const getSearchHistory = () => request<Array<{ query: string; createdAt: string; resultCount: number }>>('/search-history');
