
import { Agency, Analytics, Review } from './types';

const generateReviews = (agencyName: string, serviceType: string): Review[] => {
  const reviewsData = {
    '1': [
      { id: 'r1', author: 'John D.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Amazing SEO results! Doubled our traffic in 3 months. Highly professional team.', date: '2 weeks ago', helpfulCount: 23, verified: true },
      { id: 'r2', author: 'Sarah M.', role: 'CMO', avatar: '👩‍💼', rating: 5, text: 'Excellent PPC ROI, highly recommend. Best agency we\'ve worked with.', date: '1 month ago', helpfulCount: 18, verified: true },
      { id: 'r3', author: 'Michael Chen', role: 'VP Marketing', avatar: '👨‍💼', rating: 5, text: 'Fantastic content strategy execution. Saw immediate results.', date: '3 weeks ago', helpfulCount: 15, verified: true },
      { id: 'r4', author: 'Emma L.', role: 'Marketing Manager', avatar: '👩‍💼', rating: 4, text: 'Great team, very responsive and data-driven approach.', date: '2 months ago', helpfulCount: 12, verified: true },
      { id: 'r5', author: 'David R.', role: 'Business Owner', avatar: '👨‍💼', rating: 5, text: 'Transformed our online presence completely. Exceptional work!', date: '1 month ago', helpfulCount: 20, verified: true },
    ],
    '2': [
      { id: 'r1', author: 'Lisa K.', role: 'Social Media Manager', avatar: '👩‍💼', rating: 5, text: 'Fantastic social media strategy and execution. Engagement up 300%!', date: '3 weeks ago', helpfulCount: 21, verified: true },
      { id: 'r2', author: 'James P.', role: 'CEO', avatar: '👨‍💼', rating: 4, text: 'Very creative team. Email campaigns performed exceptionally well.', date: '1 month ago', helpfulCount: 14, verified: true },
      { id: 'r3', author: 'Rachel G.', role: 'Brand Manager', avatar: '👩‍💼', rating: 5, text: 'Excellent community management. Our followers feel valued.', date: '2 weeks ago', helpfulCount: 16, verified: true },
      { id: 'r4', author: 'Tom S.', role: 'Founder', avatar: '👨‍💼', rating: 5, text: 'Professional and creative. They really understand our brand voice.', date: '3 weeks ago', helpfulCount: 19, verified: true },
    ],
    '3': [
      { id: 'r1', author: 'Amanda T.', role: 'CMO', avatar: '👩‍💼', rating: 5, text: 'Best PPC agency we\'ve ever worked with. ROI increased by 250%!', date: '2 weeks ago', helpfulCount: 27, verified: true },
      { id: 'r2', author: 'Chris B.', role: 'VP Sales', avatar: '👨‍💼', rating: 5, text: 'Data-driven approach is fantastic. Every dollar spent is tracked and optimized.', date: '1 month ago', helpfulCount: 24, verified: true },
      { id: 'r3', author: 'Nina M.', role: 'Director of Growth', avatar: '👩‍💼', rating: 5, text: 'Incredible analytics insights. They made our campaigns much more effective.', date: '3 weeks ago', helpfulCount: 22, verified: true },
      { id: 'r4', author: 'Robert K.', role: 'Business Manager', avatar: '👨‍💼', rating: 4, text: 'Very knowledgeable team. Great communication throughout the project.', date: '1 month ago', helpfulCount: 13, verified: true },
      { id: 'r5', author: 'Jennifer W.', role: 'Marketing Lead', avatar: '👩‍💼', rating: 5, text: 'Peak Performance delivers exactly what they promise. Outstanding!', date: '2 weeks ago', helpfulCount: 25, verified: true },
    ],
    '4': [
      { id: 'r1', author: 'Kevin L.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Beautiful website design AND great SEO strategy. Two birds, one stone!', date: '1 month ago', helpfulCount: 19, verified: true },
      { id: 'r2', author: 'Michelle D.', role: 'Product Manager', avatar: '👩‍💼', rating: 4, text: 'Creative team with solid technical knowledge. Website looks amazing.', date: '3 weeks ago', helpfulCount: 16, verified: true },
      { id: 'r3', author: 'Andrew M.', role: 'Founder', avatar: '👨‍💼', rating: 5, text: 'Sunrise nailed our rebrand. Professional, creative, and timely delivery.', date: '2 weeks ago', helpfulCount: 18, verified: true },
    ],
    '5': [
      { id: 'r1', author: 'Olivia J.', role: 'Marketing Director', avatar: '👩‍💼', rating: 5, text: 'Cutting-edge strategies and beautiful design work. Love this agency!', date: '2 weeks ago', helpfulCount: 20, verified: true },
      { id: 'r2', author: 'Marcus T.', role: 'COO', avatar: '👨‍💼', rating: 5, text: 'Urban Digital really understands modern marketing. Impressed throughout.', date: '1 month ago', helpfulCount: 17, verified: true },
      { id: 'r3', author: 'Sophie R.', role: 'CMO', avatar: '👩‍💼', rating: 4, text: 'Great PPC and social media work. Very collaborative process.', date: '3 weeks ago', helpfulCount: 14, verified: true },
    ],
    '6': [
      { id: 'r1', author: 'Daniel K.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Velocity Growth helped us scale rapidly. Their growth hacking is legit!', date: '2 weeks ago', helpfulCount: 28, verified: true },
      { id: 'r2', author: 'Isabella R.', role: 'Growth Manager', avatar: '👩‍💼', rating: 5, text: 'Best growth agency ever. They cracked our email marketing code.', date: '1 month ago', helpfulCount: 26, verified: true },
      { id: 'r3', author: 'Victor S.', role: 'VP Growth', avatar: '👨‍💼', rating: 5, text: 'Exceptional SEO and analytics expertise. Saw results in weeks.', date: '3 weeks ago', helpfulCount: 23, verified: true },
      { id: 'r4', author: 'Natasha Z.', role: 'Founder', avatar: '👩‍💼', rating: 5, text: 'Velocity delivered everything promised. Highly recommend!', date: '2 weeks ago', helpfulCount: 24, verified: true },
    ],
    '7': [
      { id: 'r1', author: 'Frank B.', role: 'VP Marketing', avatar: '👨‍💼', rating: 4, text: 'Solid B2B marketing expertise. Good integration of multiple channels.', date: '3 weeks ago', helpfulCount: 12, verified: true },
      { id: 'r2', author: 'Grace H.', role: 'CMO', avatar: '👩‍💼', rating: 4, text: 'Good PPC and email campaigns. Professional team to work with.', date: '1 month ago', helpfulCount: 11, verified: true },
      { id: 'r3', author: 'Henry M.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Nexus really understands B2B sales funnel. Great results!', date: '2 weeks ago', helpfulCount: 14, verified: true },
    ],
    '8': [
      { id: 'r1', author: 'Julia C.', role: 'CMO', avatar: '👩‍💼', rating: 5, text: 'Catalyst transformed our brand narrative. Excellent content creators!', date: '2 weeks ago', helpfulCount: 17, verified: true },
      { id: 'r2', author: 'Oscar D.', role: 'CEO', avatar: '👨‍💼', rating: 4, text: 'Good SEO work and nice web design. Professional execution overall.', date: '1 month ago', helpfulCount: 13, verified: true },
      { id: 'r3', author: 'Patricia E.', role: 'Marketing Head', avatar: '👩‍💼', rating: 5, text: 'Strategic content approach worked wonderfully for us.', date: '3 weeks ago', helpfulCount: 15, verified: true },
    ],
    '9': [
      { id: 'r1', author: 'Quinn F.', role: 'Brand Manager', avatar: '👨‍💼', rating: 5, text: 'Harmony Digital crushed our influencer strategy. Authentic partnerships!', date: '2 weeks ago', helpfulCount: 19, verified: true },
      { id: 'r2', author: 'Rebecca L.', role: 'CEO', avatar: '👩‍💼', rating: 4, text: 'Good social media and content work. Collaborative and creative.', date: '1 month ago', helpfulCount: 12, verified: true },
      { id: 'r3', author: 'Samuel N.', role: 'VP Marketing', avatar: '👨‍💼', rating: 5, text: 'Expert in influencer marketing. Our brand reached new audiences!', date: '3 weeks ago', helpfulCount: 18, verified: true },
    ],
    '10': [
      { id: 'r1', author: 'Tara O.', role: 'CMO', avatar: '👩‍💼', rating: 5, text: 'Quantum Leap pushed our thinking forward. Innovative PPC strategies!', date: '2 weeks ago', helpfulCount: 25, verified: true },
      { id: 'r2', author: 'Ulysses P.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Amazing analytics insights. They made our campaigns data-driven.', date: '1 month ago', helpfulCount: 22, verified: true },
      { id: 'r3', author: 'Violet Q.', role: 'Growth Lead', avatar: '👩‍💼', rating: 5, text: 'Excellent team across all services. Highly professional.', date: '3 weeks ago', helpfulCount: 21, verified: true },
      { id: 'r4', author: 'Winston R.', role: 'Founder', avatar: '👨‍💼', rating: 4, text: 'Good email and SEO work. Reliable and professional.', date: '2 weeks ago', helpfulCount: 16, verified: true },
    ],
    '11': [
      { id: 'r1', author: 'Xander S.', role: 'Marketing Manager', avatar: '👨‍💼', rating: 4, text: 'Great design work. Websites look beautiful and modern.', date: '3 weeks ago', helpfulCount: 13, verified: true },
      { id: 'r2', author: 'Yara T.', role: 'CMO', avatar: '👩‍💼', rating: 4, text: 'Creative team with good technical skills. Happy with results.', date: '1 month ago', helpfulCount: 11, verified: true },
      { id: 'r3', author: 'Zachary U.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Prism delivered stunning visual storytelling for our brand.', date: '2 weeks ago', helpfulCount: 14, verified: true },
    ],
    '12': [
      { id: 'r1', author: 'Aurora V.', role: 'VP Growth', avatar: '👩‍💼', rating: 5, text: 'Elite Growth is in a league of their own. Enterprise-quality work!', date: '1 week ago', helpfulCount: 32, verified: true },
      { id: 'r2', author: 'Bruno W.', role: 'CEO', avatar: '👨‍💼', rating: 5, text: 'Outstanding PPC and analytics expertise. Best ROI we\'ve achieved!', date: '2 weeks ago', helpfulCount: 29, verified: true },
      { id: 'r3', author: 'Clara X.', role: 'CMO', avatar: '👩‍💼', rating: 5, text: 'Premium service deserves premium praise. Exceptional team!', date: '3 weeks ago', helpfulCount: 26, verified: true },
      { id: 'r4', author: 'Diego Y.', role: 'CFO', avatar: '👨‍💼', rating: 5, text: 'Elite Growth delivered enterprise-scale results. Highly recommend!', date: '1 month ago', helpfulCount: 28, verified: true },
      { id: 'r5', author: 'Elena Z.', role: 'Founder', avatar: '👩‍💼', rating: 5, text: 'Worth every penny. Elite Growth is worth the investment.', date: '2 weeks ago', helpfulCount: 30, verified: true },
    ],
  };

  return reviewsData[agencyName] || [];
};

export const mockAgencies: Agency[] = [
  {
    id: '1',
    name: 'Digital Growth Labs',
    logo: '🔵',
    services: ['SEO', 'PPC', 'Content'],
    rating: 4.9,
    reviewCount: 127,
    location: 'San Francisco, CA',
    state: 'CA',
    url: 'https://digitalgrowth.com',
    description: 'Award-winning digital marketing agency specializing in growth strategies.',
    badge: 'Top Rated',
    reviews: generateReviews('1', 'Digital Growth Labs'),
  },
  {
    id: '2',
    name: 'Blue Wave Marketing',
    logo: '🌊',
    services: ['Social Media', 'Email', 'Content'],
    rating: 4.7,
    reviewCount: 89,
    location: 'New York, NY',
    state: 'NY',
    url: 'https://bluewavemarketing.com',
    description: 'Experts in social media strategy and community building.',
    reviews: generateReviews('2', 'Blue Wave Marketing'),
  },
  {
    id: '3',
    name: 'Peak Performance Co',
    logo: '⛰️',
    services: ['PPC', 'SEO', 'Analytics'],
    rating: 4.8,
    reviewCount: 156,
    location: 'Chicago, IL',
    state: 'IL',
    url: 'https://peakperformance.com',
    description: 'Data-driven agency focused on measurable results and ROI.',
    badge: 'Most Reviewed',
    reviews: generateReviews('3', 'Peak Performance Co'),
  },
  {
    id: '4',
    name: 'Sunrise Marketing Partners',
    logo: '🌅',
    services: ['Web Design', 'SEO', 'Content'],
    rating: 4.6,
    reviewCount: 72,
    location: 'Austin, TX',
    state: 'TX',
    url: 'https://sunrisemarketing.com',
    description: 'Creative agency blending design and digital marketing.',
    reviews: generateReviews('4', 'Sunrise Marketing Partners'),
  },
  {
    id: '5',
    name: 'Urban Digital Studios',
    logo: '🏙️',
    services: ['Social Media', 'Web Design', 'PPC'],
    rating: 4.8,
    reviewCount: 98,
    location: 'Los Angeles, CA',
    state: 'CA',
    url: 'https://urbandigital.com',
    description: 'Cutting-edge agency specializing in urban brand development.',
    badge: 'Trending',
    reviews: generateReviews('5', 'Urban Digital Studios'),
  },
  {
    id: '6',
    name: 'Velocity Growth Hacker',
    logo: '⚡',
    services: ['SEO', 'Analytics', 'Email'],
    rating: 4.9,
    reviewCount: 134,
    location: 'Seattle, WA',
    state: 'WA',
    url: 'https://velocitygrowth.com',
    description: 'Growth-focused agency with proven scaling strategies.',
    badge: 'Top Rated',
    reviews: generateReviews('6', 'Velocity Growth Hacker'),
  },
  {
    id: '7',
    name: 'Nexus Brand Agency',
    logo: '🔗',
    services: ['PPC', 'Social Media', 'Email', 'Content'],
    rating: 4.5,
    reviewCount: 64,
    location: 'Boston, MA',
    state: 'MA',
    url: 'https://nexusbrand.com',
    description: 'Integrated marketing solutions for B2B companies.',
    reviews: generateReviews('7', 'Nexus Brand Agency'),
  },
  {
    id: '8',
    name: 'Catalyst Marketing',
    logo: '⚗️',
    services: ['SEO', 'Content', 'Web Design'],
    rating: 4.7,
    reviewCount: 81,
    location: 'Denver, CO',
    state: 'CO',
    url: 'https://catalystmkt.com',
    description: 'Agency focused on transforming brands through strategic marketing.',
    reviews: generateReviews('8', 'Catalyst Marketing'),
  },
  {
    id: '9',
    name: 'Harmony Digital Group',
    logo: '🎵',
    services: ['Social Media', 'Content', 'Analytics'],
    rating: 4.6,
    reviewCount: 76,
    location: 'Miami, FL',
    state: 'FL',
    url: 'https://harmonydigital.com',
    description: 'Specialized in influencer marketing and brand partnerships.',
    reviews: generateReviews('9', 'Harmony Digital Group'),
  },
  {
    id: '10',
    name: 'Quantum Leap Marketing',
    logo: '🚀',
    services: ['PPC', 'SEO', 'Analytics', 'Email'],
    rating: 4.8,
    reviewCount: 142,
    location: 'San Diego, CA',
    state: 'CA',
    url: 'https://quantumleap.com',
    description: 'Innovative agency pushing boundaries in digital marketing.',
    reviews: generateReviews('10', 'Quantum Leap Marketing'),
  },
  {
    id: '11',
    name: 'Prism Media Solutions',
    logo: '🎨',
    services: ['Web Design', 'Social Media', 'Content'],
    rating: 4.4,
    reviewCount: 58,
    location: 'Portland, OR',
    state: 'OR',
    url: 'https://prismmedia.com',
    description: 'Creative agency with focus on visual storytelling.',
    reviews: generateReviews('11', 'Prism Media Solutions'),
  },
  {
    id: '12',
    name: 'Elite Growth Partners',
    logo: '⭐',
    services: ['PPC', 'Analytics', 'Web Design', 'Email'],
    rating: 4.9,
    reviewCount: 168,
    location: 'Atlanta, GA',
    state: 'GA',
    url: 'https://elitegrowth.com',
    description: 'Premium agency for enterprise-level marketing solutions.',
    badge: 'Top Rated',
    reviews: generateReviews('12', 'Elite Growth Partners'),
  },
];

export const mockAnalytics: Analytics = {
  totalAgencies: 1250,
  avgRating: 4.7,
  locationsCount: 48,
  serviceBreakdown: {
    'SEO': 450,
    'PPC': 380,
    'Social Media': 420,
    'Content': 380,
    'Email': 290,
    'Web Design': 320,
    'Analytics': 210,
  },
  totalReviews: 2847,
};

export const US_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
  'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ',
  'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC',
  'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY',
];

export const SERVICES = ['SEO', 'PPC', 'Social Media', 'Content', 'Email', 'Web Design', 'Analytics'] as const;

export const SERVICE_COLORS: Record<string, string> = {
  'SEO': 'bg-green-100 text-green-700 border-green-200',
  'PPC': 'bg-orange-100 text-orange-700 border-orange-200',
  'Social Media': 'bg-pink-100 text-pink-700 border-pink-200',
  'Content': 'bg-blue-100 text-blue-700 border-blue-200',
  'Email': 'bg-purple-100 text-purple-700 border-purple-200',
  'Web Design': 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Analytics': 'bg-slate-100 text-slate-700 border-slate-200',
};
