import Agency from '../models/Agency.js'; import Review from '../models/Review.js'; import SearchHistory from '../models/SearchHistory.js'; import { AppError } from '../utils/AppError.js'; import { asyncHandler } from '../utils/asyncHandler.js'; import { calculateScore, recommendationReasons } from '../services/rankingService.js'; import { autocompleteAgencies, searchStoredAgencies } from '../services/discoveryService.js'; import { logoForDomain } from '../services/logoService.js'; import { validateWebsite } from '../services/websiteService.js';
const asClient = (agency, reviews = []) => ({ id: agency._id, name: agency.name, logo: agency.logo, services: agency.services, technologies: agency.technologies, rating: agency.rating, reviewCount: agency.reviewsCount, location: [agency.location?.city, agency.location?.state || agency.location?.country].filter(Boolean).join(', '), state: agency.location?.state || '', url: agency.website, websiteVerified: agency.websiteVerified ?? agency.verifiedWebsite, domain: agency.domain, description: agency.description, badge: agency.rankingScore >= 80 ? 'Top Rated' : undefined, rankingScore: agency.rankingScore, rankingFactors: agency.rankingFactors, recommendationReasons: recommendationReasons(agency), pricing: agency.pricing, experienceYears: agency.experienceYears || agency.yearsInBusiness, employees: agency.employees, verifiedWebsite: agency.verifiedWebsite, portfolioLinks: agency.portfolioLinks, socialLinks: agency.socialLinks, githubActivity: agency.external?.github?.activity || 0, reviews: reviews.map((review) => ({ id: review._id, userId: review.user, author: review.authorName, role: review.role, avatar: review.avatar, rating: review.rating, title: review.title, text: review.text, date: review.createdAt, createdAt: review.createdAt, updatedAt: review.updatedAt, helpfulCount: review.helpfulCount, verified: review.verified })) });
const queryFor = (query) => { const filter = { isPublished: true }; if (query.q) filter.$text = { $search: query.q }; if (query.services) filter.services = { $in: String(query.services).split(',') }; if (query.technologies) filter.technologies = { $in: String(query.technologies).split(',') }; if (query.city) filter['location.city'] = { $in: String(query.city).split(',').map((value) => new RegExp(`^${value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'i')) }; if (query.country) filter['location.country'] = { $in: String(query.country).split(',').map((value) => new RegExp(`^${value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'i')) }; if (query.minRating) filter.rating = { $gte: Number(query.minRating) }; if (query.minReviews) filter.reviewsCount = { $gte: Number(query.minReviews) }; if (query.maxPrice) filter['pricing.min'] = { $lte: Number(query.maxPrice) }; return filter; };
export const listAgencies = asyncHandler(async (req, res) => { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(100, Math.max(1, Number(req.query.limit) || 24)); const sort = req.query.sort === 'name' ? { name: 1 } : req.query.sort === 'reviewed' ? { reviewsCount: -1 } : req.query.sort === 'rating' ? { rating: -1 } : { rankingScore: -1 }; const filter = queryFor(req.query); let agencies; let total; if (req.query.q) { const result = await searchStoredAgencies({ query: req.query.q, page, limit, filters: { technologies: req.query.technologies ? String(req.query.technologies).split(',') : [], services: req.query.services ? String(req.query.services).split(',') : [], state: req.query.state, country: req.query.country, minRating: req.query.minRating }, weights: {} }); agencies = result.agencies; total = result.total; } else { [agencies, total] = await Promise.all([Agency.find(filter).sort(sort).skip((page - 1) * limit).limit(limit).lean(), Agency.countDocuments(filter)]); } const reviews = await Review.find({ agency: { $in: agencies.map((item) => item._id) }, status: 'approved' }).sort({ createdAt: -1 }).lean(); const byAgency = new Map(); reviews.forEach((review) => byAgency.set(String(review.agency), [...(byAgency.get(String(review.agency)) || []), review])); if (req.user) await SearchHistory.create({ user: req.user._id, query: req.query.q || '', filters: req.query, resultCount: total }); res.json({ success: true, data: agencies.map((agency) => asClient(agency, byAgency.get(String(agency._id)) || [])), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); });
export const getAgency = asyncHandler(async (req, res) => { const agency = await Agency.findOne({ _id: req.params.id, isPublished: true }).lean(); if (!agency) throw new AppError('Agency not found.', 404); const reviews = await Review.find({ agency: agency._id, status: 'approved' }).sort({ createdAt: -1 }).lean(); res.json({ success: true, data: asClient(agency, reviews) }); });
export const autocomplete = asyncHandler(async (req, res) => res.json({ success: true, data: await autocompleteAgencies(req.query.q || '') }));
const storedWebsiteMetadata = async (website) => {
  const metadata = await validateWebsite(website);
  return { ...metadata, verifiedWebsite: metadata.websiteVerified, logo: logoForDomain(metadata.domain), logoFetchedAt: new Date() };
};
export const createAgency = asyncHandler(async (req, res) => { const { name, website } = req.body; const normalizedName = name.toLowerCase().replace(/[^a-z0-9]/g, ''); const websiteMetadata = await storedWebsiteMetadata(website); const agency = await Agency.create({ ...req.body, ...websiteMetadata, normalizedName }); const ranking = calculateScore(agency); agency.rankingScore = ranking.score; agency.rankingFactors = ranking.factors; await agency.save(); res.status(201).json({ success: true, data: agency }); });
export const updateAgency = asyncHandler(async (req, res) => { const agency = await Agency.findById(req.params.id); if (!agency) throw new AppError('Agency not found.', 404); Object.assign(agency, req.body); if (req.body.website !== undefined) Object.assign(agency, await storedWebsiteMetadata(req.body.website)); if (req.body.name) agency.normalizedName = req.body.name.toLowerCase().replace(/[^a-z0-9]/g, ''); const ranking = calculateScore(agency); agency.rankingScore = ranking.score; agency.rankingFactors = ranking.factors; await agency.save(); res.json({ success: true, data: agency }); });
export const deleteAgency = asyncHandler(async (req, res) => { const agency = await Agency.findByIdAndDelete(req.params.id); if (!agency) throw new AppError('Agency not found.', 404); await Review.deleteMany({ agency: agency._id }); res.status(204).send(); });
