import Agency from '../models/Agency.js';
import Review from '../models/Review.js';
import { AppError } from '../utils/AppError.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { refreshAgencyRanking } from '../services/rankingService.js';

const recalculateAgencyRating = async (agencyId) => {
  const [stats] = await Review.aggregate([{ $match: { agency: agencyId, status: 'approved' } }, { $group: { _id: null, rating: { $avg: '$rating' }, count: { $sum: 1 } } }]);
  await Agency.findByIdAndUpdate(agencyId, { rating: Number((stats?.rating || 0).toFixed(1)), reviewsCount: stats?.count || 0 });
  await refreshAgencyRanking(agencyId);
};
const asClient = (review) => ({ id: review._id, userId: review.user?._id || review.user, author: review.authorName, role: review.role, avatar: review.avatar, rating: review.rating, title: review.title, text: review.text, date: review.createdAt, createdAt: review.createdAt, updatedAt: review.updatedAt, helpfulCount: review.helpfulCount, verified: review.verified, services: review.services });

export const listReviews = asyncHandler(async (req, res) => { const page = Math.max(1, Number(req.query.page) || 1); const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 10)); const filter = { agency: req.params.agencyId, status: 'approved' }; const [reviews, total, breakdown] = await Promise.all([Review.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Review.countDocuments(filter), Review.aggregate([{ $match: filter }, { $group: { _id: '$rating', count: { $sum: 1 } } }])]); const ratingBreakdown = Object.fromEntries([1, 2, 3, 4, 5].map((rating) => [rating, breakdown.find((item) => item._id === rating)?.count || 0])); res.json({ success: true, data: reviews.map(asClient), ratingBreakdown, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); });
export const createReview = asyncHandler(async (req, res) => { if (!await Agency.exists({ _id: req.params.agencyId, isPublished: true })) throw new AppError('Agency not found.', 404); if (await Review.exists({ agency: req.params.agencyId, user: req.user._id })) throw new AppError('You have already reviewed this agency. Edit or delete your existing review instead.', 409); const review = await Review.create({ agency: req.params.agencyId, user: req.user._id, authorName: req.user.name, role: 'Client', rating: req.body.rating, title: req.body.title, text: req.body.text, services: req.body.services || [] }); await recalculateAgencyRating(review.agency); res.status(201).json({ success: true, message: 'Your review has been published.', data: asClient(review) }); });
export const updateReview = asyncHandler(async (req, res) => { const review = await Review.findOne({ _id: req.params.id, user: req.user._id }); if (!review) throw new AppError('Review not found or you do not have permission to edit it.', 404); ['rating', 'title', 'text', 'services'].forEach((key) => { if (req.body[key] !== undefined) review[key] = req.body[key]; }); await review.save(); await recalculateAgencyRating(review.agency); res.json({ success: true, message: 'Review updated.', data: asClient(review) }); });
export const deleteReview = asyncHandler(async (req, res) => { const review = await Review.findOneAndDelete({ _id: req.params.id, user: req.user._id }); if (!review) throw new AppError('Review not found or you do not have permission to delete it.', 404); await recalculateAgencyRating(review.agency); res.status(204).send(); });
export const moderateReview = asyncHandler(async (req, res) => { const review = await Review.findByIdAndUpdate(req.params.id, { status: req.body.status, verified: req.body.status === 'approved' ? Boolean(req.body.verified) : false }, { new: true }); if (!review) throw new AppError('Review not found.', 404); await recalculateAgencyRating(review.agency); res.json({ success: true, data: asClient(review) }); });
