import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bookmark, MapPin } from 'lucide-react';
import { getBookmarks, removeBookmark } from '@/lib/api';
import { AgencyLogo } from '@/components/agency-logo';
import { useToast } from '@/components/ui/use-toast';

type SavedAgency = { id: string; name: string; logo?: string; description?: string; location?: { city?: string; state?: string; country?: string } | string; services?: string[]; rating?: number };
export default function Bookmarks() {
  const [agencies, setAgencies] = useState<SavedAgency[]>([]); const [loading, setLoading] = useState(true); const { toast } = useToast();
  const load = async () => { setLoading(true); try { const result = await getBookmarks(); setAgencies(result.data.map((item) => item.agency as SavedAgency).filter(Boolean)); } catch (error) { toast({ title: 'Unable to load bookmarks', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const remove = async (id: string) => { try { await removeBookmark(id); setAgencies((items) => items.filter((agency) => agency.id !== id)); toast({ title: 'Bookmark removed' }); } catch { toast({ title: 'Unable to remove bookmark', variant: 'destructive' }); } };
  return <main className="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-950"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">Your shortlist</p><h1 className="mt-2 text-3xl font-extrabold">Saved agencies</h1><p className="mt-2 text-slate-500">Keep track of the teams you may want to work with.</p></div><Link to="/" className="rounded-xl bg-primary px-4 py-2.5 font-semibold text-white">Explore agencies</Link></div>{loading ? <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-56 animate-pulse rounded-2xl bg-white dark:bg-slate-900" />)}</div> : agencies.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{agencies.map((agency) => { const place = typeof agency.location === 'string' ? agency.location : [agency.location?.city, agency.location?.state || agency.location?.country].filter(Boolean).join(', '); return <article key={agency.id} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><AgencyLogo name={agency.name} src={agency.logo} /><button onClick={() => remove(agency.id)} aria-label={`Remove ${agency.name}`} className="rounded-lg p-2 text-primary hover:bg-blue-50 dark:hover:bg-blue-950"><Bookmark className="h-5 fill-current" /></button></div><Link to={`/agency/${agency.id}`} className="mt-4 block text-lg font-bold hover:text-primary">{agency.name}</Link><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin className="h-3.5" /> {place || 'Location available on profile'}</p><p className="mt-3 line-clamp-2 text-sm text-slate-600 dark:text-slate-300">{agency.description || 'View this agency profile for services, reviews, and project information.'}</p><div className="mt-4 flex flex-wrap gap-1.5">{agency.services?.slice(0, 3).map((service) => <span key={service} className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-950 dark:text-blue-200">{service}</span>)}</div></article>; })}</div> : <div className="mt-8 rounded-2xl border border-dashed bg-white p-12 text-center dark:bg-slate-900"><Bookmark className="mx-auto h-8 text-primary" /><h2 className="mt-4 text-xl font-bold">Your shortlist is empty</h2><p className="mt-2 text-slate-500">Bookmark agencies from their profile to compare them later.</p><Link to="/" className="mt-5 inline-block font-semibold text-primary">Discover agencies</Link></div>}</div></main>;
}
