import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Bookmark, Clock3, Settings2, Star } from 'lucide-react';
import { changePassword, getBookmarks, getProfile, getSearchHistory, updateProfile } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { useToast } from '@/components/ui/use-toast';
import { AgencyLogo } from '@/components/agency-logo';
import { Agency } from '@/lib/types';

type ProfileData = { id: string; name: string; email: string; createdAt?: string; reviewsWritten: number; savedAgencies: number };
export default function Profile() {
  const { user, setUser } = useAuth(); const { toast } = useToast();
  const [profile, setProfile] = useState<ProfileData | null>(null); const [name, setName] = useState(user?.name || ''); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState('');
  const [saved, setSaved] = useState<Agency[]>([]); const [searches, setSearches] = useState<Array<{ query: string; createdAt: string; resultCount: number }>>([]);
  useEffect(() => { Promise.all([getProfile(), getBookmarks(), getSearchHistory()]).then(([account, bookmarks, history]) => { setProfile(account.data); setName(account.data.name); setSaved(bookmarks.data.map((item) => item.agency).filter(Boolean)); setSearches(history.data); }).catch(() => toast({ title: 'Unable to load dashboard', variant: 'destructive' })); }, []);
  const saveProfile = async (event: FormEvent) => { event.preventDefault(); try { const result = await updateProfile(name); setUser(result.user || null); setProfile((value) => value && { ...value, name }); toast({ title: 'Profile updated' }); } catch (error) { toast({ title: 'Unable to update profile', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } };
  const savePassword = async (event: FormEvent) => { event.preventDefault(); try { await changePassword(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); toast({ title: 'Password changed' }); } catch (error) { toast({ title: 'Unable to change password', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } };
  return <main className="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-950"><div className="mx-auto max-w-6xl"><div className="mb-8"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-500"><Link to="/" className="hover:text-primary">Home</Link> <span className="px-1">/</span> Dashboard</p><p className="mt-3 text-sm font-bold uppercase tracking-widest text-primary">Your workspace</p><h1 className="mt-2 text-3xl font-extrabold">Account dashboard</h1><p className="mt-2 text-slate-500">Manage your agency research, saved partners, and account.</p></div><Link to="/" className="shrink-0 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold shadow-sm transition hover:bg-slate-50 dark:bg-slate-900 dark:hover:bg-slate-800">← Back to Home</Link></div></div><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><div className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 text-xl font-bold text-white">{user?.name?.[0]?.toUpperCase()}</div><div><h2 className="text-xl font-bold">{user?.name}</h2><p className="text-slate-500">{user?.email}</p><p className="text-xs text-slate-400">Member since {profile?.createdAt ? new Date(profile.createdAt).toLocaleDateString() : '—'}</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div id="reviews" className="rounded-xl bg-blue-50 p-4 dark:bg-blue-950/40"><Star className="h-4 text-primary" /><b className="mt-2 block text-2xl">{profile?.reviewsWritten ?? 0}</b><span className="text-sm text-slate-500">Reviews written</span></div><div className="rounded-xl bg-violet-50 p-4 dark:bg-violet-950/40"><Bookmark className="h-4 text-violet-600" /><b className="mt-2 block text-2xl">{profile?.savedAgencies ?? 0}</b><span className="text-sm text-slate-500">Saved agencies</span></div></div></section><section className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Saved agencies</h2><Link to="/bookmarks" className="text-sm font-semibold text-primary">View all</Link></div>{saved.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{saved.slice(0, 6).map((agency) => <Link key={agency.id} to={`/agency/${agency.id}`} className="flex items-center gap-3 rounded-xl border p-3 transition hover:border-primary/30 hover:shadow-sm"><AgencyLogo name={agency.name} src={agency.logo} className="h-11 w-11 rounded-xl" /><span className="min-w-0"><b className="block truncate">{agency.name}</b><small className="block truncate text-slate-500">
    {/* {agency.location} */}
    [
  agency.location?.city,
  agency.location?.state,
  agency.location?.country
]
.filter(Boolean)
.join(", ")
    </small></span></Link>)}</div> : <p className="mt-4 rounded-xl bg-slate-50 p-5 text-sm text-slate-500 dark:bg-slate-800">Save agencies from their profile to keep your shortlist here.</p>}</section></div><aside className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="flex items-center gap-2 text-xl font-bold"><Clock3 className="h-5 text-primary" /> Recent searches</h2>{searches.length ? <div className="mt-4 space-y-3">{searches.slice(0, 5).map((search, index) => <div key={`${search.createdAt}-${index}`} className="border-b pb-3 last:border-0"><p className="font-medium">{search.query || 'Browse agencies'}</p><p className="text-xs text-slate-500">{search.resultCount} results · {new Date(search.createdAt).toLocaleDateString()}</p></div>)}</div> : <p className="mt-4 text-sm text-slate-500">Your discovery searches will appear here.</p>}</section><form id="settings" onSubmit={saveProfile} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="flex items-center gap-2 text-xl font-bold"><Settings2 className="h-5 text-primary" /> Account settings</h2><label className="block text-sm font-medium">Name<input required minLength={2} value={name} onChange={(event) => setName(event.target.value)} className="mt-1.5 w-full rounded-lg border bg-transparent p-2.5" /></label><button className="rounded-lg bg-primary px-4 py-2 font-semibold text-white">Save changes</button></form><form onSubmit={savePassword} className="space-y-3 rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="text-lg font-bold">Change password</h2><input required minLength={8} type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} placeholder="Current password" className="w-full rounded-lg border bg-transparent p-2.5" /><input required minLength={8} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} placeholder="New password" className="w-full rounded-lg border bg-transparent p-2.5" /><button className="rounded-lg border px-4 py-2 font-semibold">Update password</button></form></aside></div></div></main>;
}
