import { Bookmark, ExternalLink, Mail, MapPin } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Agency } from '@/lib/types';
import { StarRating } from './star-rating';
import { AgencyLogo } from './agency-logo';
import { addBookmark, removeBookmark } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { useToast } from './ui/use-toast';

interface AgencyCardProps { agency: Agency; onReviewSubmitted?: () => void; view?: 'grid' | 'list'; }
export function AgencyCard({ agency, view = 'grid' }: AgencyCardProps) {
  const { user } = useAuth(); const navigate = useNavigate(); const { toast } = useToast(); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false);
  const toggleSaved = async () => { if (!user) { navigate('/login', { state: { from: window.location.pathname } }); return; } setSaving(true); try { if (saved) await removeBookmark(agency.id); else await addBookmark(agency.id); setSaved((value) => !value); toast({ title: saved ? 'Removed from bookmarks' : 'Agency saved' }); } catch (error) { toast({ title: 'Unable to update bookmark', description: error instanceof Error ? error.message : '', variant: 'destructive' }); } finally { setSaving(false); } };
  const services = agency.services.slice(0, 3); const moreServices = Math.max(0, agency.services.length - services.length);
  return <article className={`group overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl hover:shadow-slate-900/10 dark:border-slate-800 dark:bg-slate-900 ${view === 'list' ? 'flex flex-col gap-5 sm:flex-row sm:items-center' : 'flex h-[440px] flex-col'}`}>
    <div className={view === 'list' ? 'flex shrink-0 items-start gap-4' : 'flex items-start justify-between'}><AgencyLogo name={agency.name} src={agency.logo} /><button onClick={toggleSaved} disabled={saving} aria-label={saved ? `Remove ${agency.name} bookmark` : `Save ${agency.name}`} className={`rounded-xl border p-2.5 transition hover:border-primary/30 hover:bg-blue-50 disabled:opacity-50 dark:hover:bg-blue-950 ${saved ? 'border-primary text-primary' : 'text-slate-500 dark:border-slate-700'}`}><Bookmark className={`h-4 w-4 ${saved ? 'fill-current' : ''}`} /></button></div>
    <div className={`min-w-0 ${view === 'list' ? 'flex-1' : ''}`}><div className="flex flex-wrap items-center gap-2"><Link to={`/agency/${agency.id}`} className="truncate text-lg font-bold tracking-tight transition hover:text-primary">{agency.name}</Link>{agency.badge && <span className="rounded-full bg-gradient-to-r from-blue-600 to-violet-600 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-white">AI Match</span>}</div><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="h-3.5 w-3.5" /> {agency.location}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{agency.description || 'Explore this agency’s services, client feedback, and company profile.'}</p><div className="mt-4 flex flex-wrap gap-2">{services.map((service) => <span key={service} className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700 dark:bg-slate-800 dark:text-slate-200">{service}</span>)}{moreServices ? <span className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-semibold text-primary dark:bg-blue-950">+{moreServices} more</span> : null}</div></div>
    <div className={`${view === 'list' ? 'sm:ml-auto sm:w-52' : 'mt-auto'} pt-4`}><div className="min-h-6">{agency.reviewCount ? <StarRating rating={agency.rating} count={agency.reviewCount} size="sm" /> : <StarRating rating={0} count={0} size="sm" />}</div><div className="mt-4 flex items-center gap-2"><Link to={`/agency/${agency.id}`} className="flex-1 rounded-xl bg-primary px-3 py-2.5 text-center text-sm font-semibold text-white transition hover:bg-blue-700 hover:shadow-md">View Details</Link>{agency.websiteVerified ? <a href={agency.url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${agency.name} website`} className="rounded-xl border p-2.5 text-slate-600 transition hover:border-primary/30 hover:text-primary dark:border-slate-700 dark:text-slate-300"><ExternalLink className="h-4 w-4" /></a> : null}<a href={`mailto:?subject=${encodeURIComponent(`Agency enquiry: ${agency.name}`)}`} aria-label={`Contact ${agency.name}`} className="rounded-xl border p-2.5 text-slate-600 transition hover:border-primary/30 hover:text-primary dark:border-slate-700 dark:text-slate-300"><Mail className="h-4 w-4" /></a></div></div>
  </article>;
}
